# Parse images into input vector from training set

In [ ]:
from keras.preprocessing import image
import numpy as np
import os

dataPath = 'RealImageNet/ImageNetSubsample/Data/CLS-LOC'
trainPath = os.path.join(dataPath, 'train')
testPath = os.path.join(dataPath, 'test')
trainPath = os.path.join(dataPath, 'train')
validationPath = os.path.join(dataPath, 'val')

trainingFolders = [x for x in os.listdir(trainPath)]

lines = [line.rstrip('\n').split() for line in open('RealImageNet/LOC_synset_mapping.txt')]
# print(lines)
wnids_to_words = {line[0]:' '.join(line[1:]) for line in lines }

train_bboxes = {} #{image_name: list(bboxes)}
for id in trainingFolders:
    boxesPath = os.path.join("RealImageNet", "LOC_train_solution.csv")
    lines = [line.rstrip('\n').split(',') for line in open(boxesPath)][1:]
    for line in lines:
        imageId = line[0]
        predictionString = line[1]
        split = predictionString.split()
        train_bboxes[imageId] = []
        for i in range(0, len(split), 5):
            box = split[i:i+5]
            train_bboxes[imageId].append(box)

for imageName in train_bboxes.keys():
    imagePath = os.path.join(trainPath, imageName.split('_')[0], imageName + ".JPEG")
    if os.path.exists(imagePath):
        img = image.load_img(imagePath, target_size=(224, 224))
        x = image.img_to_array(img)  
        print(x)
        x = np.expand_dims(x, axis=0)                          # making a numpy array
        print(x)
    
            


[[[ 92. 105.  62.]
  [ 68. 119.  18.]
  [ 51.  67.  38.]
  ...
  [108. 130.  45.]
  [116. 125.  60.]
  [153. 162.  83.]]

 [[ 83. 134.  55.]
  [ 43.  72.  16.]
  [ 90. 122.  39.]
  ...
  [123. 171.  72.]
  [ 82. 111.  57.]
  [111. 130.  40.]]

 [[ 89. 109.  46.]
  [ 54.  86.  11.]
  [ 56. 110.  24.]
  ...
  [ 54.  74.  25.]
  [121. 138.  67.]
  [101. 118.  47.]]

 ...

 [[ 96. 110.  75.]
  [ 61.  95.  44.]
  [ 49.  59.  22.]
  ...
  [ 87.  99.  53.]
  [109. 107.  84.]
  [128. 119.  90.]]

 [[ 94. 122.  99.]
  [ 71.  88.  44.]
  [ 91. 102.  46.]
  ...
  [133. 124. 119.]
  [128. 115. 109.]
  [128. 123. 119.]]

 [[ 62.  84.  61.]
  [102. 146.  97.]
  [ 70.  81.  39.]
  ...
  [110. 103.  93.]
  [129. 116. 107.]
  [113. 106.  96.]]]
[[[[ 92. 105.  62.]
   [ 68. 119.  18.]
   [ 51.  67.  38.]
   ...
   [108. 130.  45.]
   [116. 125.  60.]
   [153. 162.  83.]]

  [[ 83. 134.  55.]
   [ 43.  72.  16.]
   [ 90. 122.  39.]
   ...
   [123. 171.  72.]
   [ 82. 111.  57.]
   [111. 130.  40.]]

  [[

In [ ]:
from keras.preprocessing import image
import numpy as np

# LATER: Add the image net parsing here, then do for-loop
#             

img_path = 'elephant.jpg'
img = image.load_img(img_path, target_size=(224, 224)) # kil format based on pillow -> loads to certain size
x = image.img_to_array(img)                            
x = np.expand_dims(x, axis=0)                          # making a numpy array

preds = model.predict(x)
# decode the results into a list of tuples (class, description, probability)
# (one such list for each sample in the batch)
print('Predicted:', decode_predictions(preds, top=3)[0])
# Predicted: [(u'n02504013', u'Indian_elephant', 0.82658225), (u'n01871265', u'tusker', 0.1122357), (u'n02504458', u'African_elephant', 0.061040461)]

# Set up and train model 

In [ ]:
from keras.models import Sequential # How layers interact (x -> y)
from keras.layers import Dense      # Type of layer (what you feed your data into)

x_train, y_train = None

model = Sequential()
model.add(Dense(units=256, activation="softmax"))

# LATER: Specify input shape!!

#define metrics, loss function (maybe our own?), gradient descent
model.compile(loss = "categorical_crossentropy", metrics = ["accuracy"], optimizer = "adam")

# Train model
model.fit(x_train, y_train, epochs = 10)

# Validate

# Evaluate


# Train a model to classify